dist: xenial
language: python

cache: pip
before_install:
  - pip install --upgrade pip
install:
  - pip install tox
  - pip install coveralls
script:
  - tox
after_success:
  - coveralls

jobs:
  include:
    - python: '3.5'
      env: TOXENV=py35-dj22
    - python: '3.6'
      env: TOXENV=py36-dj22
    - python: '3.6'
      env: TOXENV=py36-dj32
    - python: '3.7'
      env: TOXENV=py37-dj22
    - python: '3.7'
      env: TOXENV=py37-dj32
    - python: '3.8'
      env: TOXENV=py38-dj22
    - python: '3.8'
      env: TOXENV=py38-dj32
    - python: '3.8'
      env: TOXENV=py38-dj40
    - python: '3.9'
      env: TOXENV=py39-dj22
    - python: '3.9'
      env: TOXENV=py39-dj32
    - python: '3.9'
      env: TOXENV=py39-dj40
    - python: '3.10'
      env: TOXENV=py310-dj32
    - python: '3.10'
      env: TOXENV=py310-dj40

    - python: '3.8'
      env: TOXENV=lint

    - stage: release
      python: '3.8'
      if: tag IS present
      deploy:
        provider: pypi
        user: Praekelt
        password:
          secure: O0feip8iJtd8Pulu2m9qcAg2yqwBUe5FsvYSaWTJke8a9oiS4xGittATKqbxUZNvFjHpbS79V2032IPDs+oNePwotSavPiKeSF1xNxAaeGuEH7nFuaYQ4/RzLpHHYU3KT61sa32U+bdH3AoDvAb/5MzlLucTVGLEuCUpHXLhcx0=
        distributions: sdist bdist_wheel
        on: {tags: true}

      install: skip
      script: skip
